apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chocott-backstage-daylight55
  description: Chocott Backstage created by daylight55
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: daylight55@example.com
  lifecycle: experimental
