version: '3'

services:
  backstage:
    #image: ghcr.io/ap-communications/chocott-backstage:1.5.0
    image: backstage:latest
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    volumes:
      # - "./app-config.local.yaml:/app/config/app-config.yaml"
      - "./app-config.chocott.yaml:/app/config/app-config.yaml"
      - "${GITHUB_CREDENTIAL_FILE}:/app/config/github-credentials.yaml"
    command:
      - "--config"
      - "/app/config/app-config.yaml"
    ports:
      - 7007:7007
    env_file:
      - .env
    environment:
      GITHUB_CREDENTIAL_FILE: /app/config/github-credentials.yaml
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    restart: always
    ports:
      - 5432:5432
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 250M

networks:
  backend:
